#!/bin/sh
# maybe some day test rsync dry runs
#rsyncig diff files to each other

function test_run () {
	for size in 1 100 1024
	do
		cp $pool/data-random-$size $rsync_src
		# from scratch
		measure_rsync
		# no-op
		rm $rsync_src/data-random-$size
	done
}
