#!/bin/sh

set -e

. ${XDG_CONFIG_HOME:-$HOME/.config}/rsyncbench/config
for var in src dst pool init_pool init_src init_dst tcpdump_cmd tcpdump_stop
do
	if [[ -z ${!var} ]]
	then
		echo "variable $var is not set!" >&2
		exit 2
	fi
done
$init_pool
$init_src
$init_dst
echo "Initialising data useful for all tests"
for size in 1 100 1024
do
	echo "creating random file, $size MiB big, if needed"
	[ -f $pool/data-random-$size ] || dd if=/dev/urandom of=$pool/data-random-$size bs=1024k count=$size # hard to compress
	echo "creating file full of zeroes, $size MiB big, if needed"
	[ -f $pool/data-zeroes-$size ] || dd if=/dev/zero    of=$pool/data-zeroes-$size bs=1024k count=$size # easy to compress
done

echo "creating empty file, if needed"
	[ -f $pool/data-empty ] || touch $pool/data-empty

function measure_rsync () {
	$tcpdump_cmd &
	time_before=$(date +%s)
	bytes_sent_comp=$(rsync -av --delete $src/ $dst/ | awk '/^sent [^ ]* bytes/ { print $2}')
	kiB_sent_comp=$((bytes_sent_comp / 1024))
	time_after=$(date +%s)
	eval $tcpdump_stop || true # for some reason, this returns false even when it worked.. so we assume it always works.
	bytes_sent=$(stat -c %s /tmp/rsyncpackets)
	kiB_sent=$((bytes_sent / 1024))
	duration=$((time_after - time_before))
}

# override these in plugins
function test_init () {
	true
}
function test_run () {
	true
}
function test_graph () {
	true
}
cd src/tests
for testrun in *.sh
do
	# i don't really see a reason this should be per-testrun, seems to make more sense to do this globally
	# so that different tests have access to each other files
	echo "Initialising data specifically for $testrun"
	. ./$testrun
	test_init
done

for testrun in *.sh
do
	echo "RUNNING TESTRUN $testrun"
	. ./$testrun
	test_run
	test_graph
done
